### ISSUE TITLE
DRC dialog is missing variable assignment arrows

### ISSUE THREAD

**Issue by BobMuenchen** [BlueSkyStatistics/dialogs-model-fitting#5]
All of the other BlueSky dialogs have assignment arrows that transfer variables from the var list to the role boxes. The DRC dialog is missing those for the top two boxes. Perhaps because of this, when the variable is moved into the role box, it changes font from the BlueSky standard to Courier.

I don't see the usual labels in this new area of Github, so I'm leaving them blank.

**Comment by adpgithub** [comment]
The first 2 controls are the smart input controls (not the ordinary control). The smart control allows you create expression by dragging multiple variables. Smart input control does not come with an assignment arrow.

**Comment by BobMuenchen** [comment]
I remember Sanjay telling me that now. Thanks for the reminder!
